// common.h 
#include <algorithm>
#include <chrono>
#include <inttypes.h>
#include <iostream>
#include <fstream>
#include <cmath>
#include <typeinfo>
#include <map>
#include <sstream>
#include <string>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <string>
#include <thread>
#include <unordered_map>
#include <vector>
#include <thread>
#include <mutex>