#Makefile 
CPP = g++
FLAGS = -Wall -std=c++14
# SRCS = main.cpp Rule.cpp Fact.cpp Manipulator.cpp 
# OBJ = main.o Rule.o Fact.o Manipulator.o

all: sri

sri: main.o Manipulator.o Rule.o Fact.o
	$(CPP) $(FLAGS) -o sri main.o Manipulator.o Rule.o Fact.o

main.o: main.cpp
	$(CPP) $(FLAGS) -c main.cpp
	
Manipulator.o: Manipulator.cpp Manipulator.h
	$(CPP) $(FLAGS) -c Manipulator.cpp

Rule.o: Rule.cpp Rule.h common.h
	$(CPP) $(FLAGS) -c Rule.cpp

Fact.o: Fact.cpp Fact.h common.h
	$(CPP) $(FLAGS) -c Fact.cpp
	 
