#Makefile 
#jk CPP = g++
# FLAGS = -g -Wall
# SRCS = main.cpp Rule.cpp Fact.cpp Manipulator.cpp 
# OBJ = main.o Rule.o Fact.o Manipulator.o

all: SRI

SRI: main.o Manipulator.o Rule.o Fact.o
	g++ main.o Manipulator.o Rule.o Fact.o -o SRI

main.o: main.cpp
	g++ -c main.cpp
	
Manipulator.o: Manipulator.cpp Manipulator.h
	g++ -c Manipulator.cpp

Rule.o: Rule.cpp Rule.h common.h
	g++ -c Rule.cpp

Fact.o: Fact.cpp Fact.h common.h
	g++ -c Fact.cpp
	 
